name: flutter_file_picker
description: File Picker for AliothX
version: 
homepage : https://github.com/reactspring
repository: https://github.com/reactspring/flutter_file_picker.git
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_plugin_android_lifecycle: ^2.0.9
  plugin_platform_interface: ^2.1.4
  ffi: ^1.2.1
  path:

dev_dependencies:
  lints: ^2.0.1
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.mr.flutter.plugin.filepicker
        pluginClass: FilePickerPlugin
      ios:
        pluginClass: FilePickerPlugin
